services:
  db:
    image: pgvector/pgvector:pg15
    container_name: daily_quotes_container_db
    restart: always
    environment:
      POSTGRES_USER: costin
      POSTGRES_PASSWORD: costin
      POSTGRES_DB: daily_quotes_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: